# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsn', models.CharField(max_length=8)),
                ('size', models.CharField(help_text='Module size in GB', max_length=10)),
                ('free', models.CharField(help_text='Free space', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='rdsi, godzilla16, cornucopia....', max_length=100)),
                ('location', models.CharField(help_text='IP address', max_length=100)),
                ('port', models.CharField(help_text='Port number', max_length=100)),
                ('freespace', models.CharField(help_text='Available space in TB', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='expinstance',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Module'),
        ),
    ]
