# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170601_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('r', 'Rapid'), ('ra', 'Radioastron'), ('a', 'Austral')], help_text='Enter experiment type (e.g. rapid, radioastron, austral)', max_length=2),
        ),
    ]
