# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170601_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.ForeignKey(help_text='Select a type for this experiment', on_delete=django.db.models.deletion.CASCADE, to='catalog.Type'),
        ),
    ]
