# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170601_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
