# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_experiment_correlation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expinstance',
            old_name='mod_status',
            new_name='module_to_raid',
        ),
        migrations.RenameField(
            model_name='expinstance',
            old_name='transfer_status',
            new_name='transfer_to_correlator',
        ),
    ]
