# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170602_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expinstance',
            old_name='experiment',
            new_name='name',
        ),
    ]
