# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170602_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expinstance',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Experiment'),
        ),
    ]
