# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170602_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expinstance',
            name='module',
        ),
        migrations.AddField(
            model_name='expinstance',
            name='module',
            field=models.ManyToManyField(to='catalog.Module'),
        ),
    ]
