# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170602_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expinstance',
            name='module',
        ),
        migrations.AddField(
            model_name='expinstance',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Module'),
        ),
    ]
