# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170602_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expinstance',
            name='module',
        ),
        migrations.AddField(
            model_name='expinstance',
            name='module',
            field=models.ManyToManyField(null=True, to='catalog.Module'),
        ),
    ]
