# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20170605_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expinstance',
            name='module',
            field=models.ManyToManyField(to='catalog.Module'),
        ),
    ]
