# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20170606_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='location',
        ),
        migrations.AddField(
            model_name='raid',
            name='ip',
            field=models.CharField(blank=True, help_text='IP address', max_length=16),
        ),
        migrations.AddField(
            model_name='raid',
            name='path',
            field=models.CharField(blank=True, help_text='file system path', max_length=100),
        ),
    ]
