# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20170606_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='freespace',
            field=models.DecimalField(decimal_places=1, help_text='Available space in TB one decimal place', max_digits=4),
        ),
    ]
