# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20170606_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='expinstance',
            name='scans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
