# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_expinstance_scans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpInstance',
            new_name='ExperimentInstance',
        ),
    ]
