# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20170727_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Select a type for this experiment', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Type'),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Experiment'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('r', 'Rapid'), ('ra', 'Radioastron'), ('a', 'Austral'), ('lba', 'LBA')], help_text='Enter experiment type (e.g. rapid, radioastron, austral)', max_length=2),
        ),
    ]
