# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20170815_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='id',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
