# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20170815_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentinstance',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='experimentinstance',
            name='module',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='ExperimentInstance',
        ),
    ]
