# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20170816_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateField(blank=True, null=True)),
                ('scans', models.IntegerField(blank=True, null=True)),
                ('sched_size', models.IntegerField(help_text='Scheduled experiment data GB', null=True)),
                ('rec_size', models.IntegerField(help_text='Recorded experiment data GB', null=True)),
                ('station', models.CharField(blank=True, choices=[('ke', 'Katherine'), ('ho', 'Hobart26'), ('hb', 'Hobart12'), ('yg', 'Yarragadee')], help_text='Station two letter i.d.', max_length=2)),
                ('module_to_raid', models.CharField(blank=True, choices=[('p', 'Pending copy'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Module upload to raid status', max_length=1)),
                ('transfer_to_correlator', models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Transfer to correlator status', max_length=1)),
                ('data_status', models.CharField(blank=True, choices=[('n', 'Not deleted'), ('p', 'Pending, correlated'), ('d', 'Deleted')], default='n', help_text='Data on module status', max_length=1)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Experiment')),
                ('module', models.ManyToManyField(to='catalog.Module')),
            ],
            options={
                'ordering': ['recorded'],
            },
        ),
    ]
