# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_experimentinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='data_status',
            field=models.CharField(blank=True, choices=[('n', 'Not deleted'), ('p', 'Pending, correlated'), ('d', 'Deleted')], default='n', help_text='Data on module status', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='module_to_raid',
            field=models.CharField(blank=True, choices=[('p', 'Pending copy'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Module upload to raid status', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='transfer_to_correlator',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Transfer to correlator status', max_length=1, null=True),
        ),
    ]
