# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20170816_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentinstance',
            name='raid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Raid'),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='station',
            field=models.CharField(blank=True, choices=[('ke', 'Katherine'), ('ho', 'Hobart26'), ('hb', 'Hobart12'), ('yg', 'Yarragadee'), ('cd', 'Ceduna')], help_text='Station two letter i.d.', max_length=2),
        ),
    ]
