# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20170822_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='id',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('r', 'Rapid'), ('ra', 'Radioastron'), ('aus', 'Austral'), ('lba', 'LBA')], help_text='Enter experiment type (e.g. rapid, radioastron, austral)', max_length=2, primary_key=True, serialize=False),
        ),
    ]
