# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20170822_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='name',
            new_name='server',
        ),
    ]
