# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20170905_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='freespace',
            field=models.DecimalField(decimal_places=1, help_text='Available space in TB one decimal place', max_digits=4, null=True),
        ),
    ]
