# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20170913_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='id',
        ),
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(choices=[('bfg8', '/mnt/bfg8'), ('bfg16', '/mnt/bfg16'), ('IVS', '/mnt/rdsi/IVS'), ('godzilla8', '/mnt/godzilla8'), ('godzilla16', '/mnt/godzilla16'), ('cornucopia', '/mnt/cornucopia'), ('AUSTRAL', '/mnt/rdsi/AUSTRAL'), ('astro', '/mnt/rdsi/astro'), ('sirius8', '/mnt/sirius8'), ('sirius16', '/mnt/sirius16')], max_length=16, primary_key=True, serialize=False),
        ),
    ]
