# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20170913_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('rivs', 'Rapid IVS'), ('ivs', 'IVS'), ('ra', 'Radioastron'), ('aus', 'Austral'), ('lba', 'LBA')], help_text='Enter experiment type (e.g. rapid, radioastron, austral)', max_length=2, primary_key=True, serialize=False),
        ),
    ]
