# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20170927_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['schedate']},
        ),
    ]
