# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20170927_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='station',
            field=models.CharField(blank=True, choices=[('ke', 'Katherine'), ('ho', 'Hobart26'), ('hb', 'Hobart12'), ('yg', 'Yarragadee'), ('cd', 'Ceduna'), ('ti', 'Tidbinbilla')], help_text='Station two letter i.d.', max_length=2),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='transfer_to_correlator',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], help_text='Transfer to correlator status', max_length=1, null=True),
        ),
    ]
