# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20171011_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='free',
            field=models.IntegerField(blank=True, help_text='Free space in GB', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='size',
            field=models.IntegerField(blank=True, help_text='Module size in GB', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='vsn',
            field=models.CharField(max_length=10),
        ),
    ]
