# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20171012_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentinstance',
            old_name='module',
            new_name='modules',
        ),
    ]
