# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20171012_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.AlterField(
            model_name='module',
            name='vsn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
