# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20171018_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentinstance',
            name='modules',
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='module',
            field=models.ManyToManyField(blank=True, to='catalog.Module'),
        ),
    ]
