# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20171018_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Module'),
        ),
    ]
