# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20171025_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentinstance',
            old_name='module',
            new_name='disk_pack',
        ),
    ]
