# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20171025_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentinstance',
            name='disk_pack',
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='module',
            field=models.ManyToManyField(help_text='Module vsn', to='catalog.Module'),
        ),
    ]
