# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20171101_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='module',
            field=models.ManyToManyField(blank=True, help_text='Module vsn', to='catalog.Module'),
        ),
    ]
