# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20171115_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='transfer_to_correlator',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Transfer to correlator status', max_length=1, null=True),
        ),
    ]
