# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20171116_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('rivs', 'Rapid IVS'), ('ivs', 'IVS'), ('ra', 'Radioastron'), ('aus', 'Austral'), ('lba', 'LBA'), ('cont', 'CONT')], help_text='Enter experiment type (e.g. rapid, radioastron, austral)', max_length=4, primary_key=True, serialize=False),
        ),
    ]
