# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_auto_20171221_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(choices=[('bfg8', '/mnt/bfg8'), ('bfg16', '/mnt/bfg16'), ('IVS', '/mnt/rdsi/IVS'), ('godzilla8', '/mnt/godzilla8'), ('godzilla16', '/mnt/godzilla16'), ('cornucopia', '/mnt/cornucopia'), ('AUSTRAL', '/mnt/rdsi/AUSTRAL'), ('astro', '/mnt/rdsi/astro'), ('LBA', '/mnt/rdsi/LBA'), ('jupiter', '/mnt/RAID'), ('jupiter2', '/mnt/RAID2'), ('sirius8', '/mnt/sirius8'), ('sirius16', '/mnt/sirius16'), ('flexbuf3', '/mnt/flexbuf3'), ('flexbuf2', '/mnt/flexbuf2'), ('flexbuf1', '/mnt/flexbuf1'), ('flexbuf0', '/mnt/flexbuf0'), ('vortex', 'exports/vortex_internal')], max_length=16, primary_key=True, serialize=False),
        ),
    ]
