# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-03 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20180730_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='location',
            field=models.CharField(blank=True, choices=[('ke', 'Katherine'), ('ho', 'Hobart'), ('yg', 'Yarragadee'), ('cd', 'Ceduna'), ('ti', 'Tidbinbilla')], help_text='Station two letter i.d.', max_length=2),
        ),
    ]
