# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_auto_20180816_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlator',
            name='name',
            field=models.CharField(choices=[('BONN', 'Bonn'), ('HAYS', 'Haystack'), ('WASH', 'Washington'), ('SHAO', 'Shanghai'), ('VLBA', 'VLBA'), ('GSI', 'Geoscience Institute'), ('VIEN', 'Vienna'), ('CURT', 'Curtin'), ('HOB', 'Hobart'), ('CASS', 'ATNF')], max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(choices=[('bfg8', '/mnt/bfg8'), ('bfg16', '/mnt/bfg16'), ('IVS', '/mnt/rd1/IVS'), ('godzilla8', '/mnt/godzilla8'), ('godzilla16', '/mnt/godzilla16'), ('cornucopia', '/mnt/cornucopia'), ('AUSTRAL', '/mnt/rd1/AUSTRAL'), ('astro', '/mnt/rd1/astro'), ('LBA', '/mnt/rd1/LBA'), ('jupiter', '/mnt/RAID'), ('jupiter2', '/mnt/RAID2'), ('sirius8', '/mnt/sirius8'), ('sirius16', '/mnt/sirius16'), ('flexbuf3', '/mnt/flexbuf3'), ('flexbuf2', '/mnt/flexbuf2'), ('flexbuf1', '/mnt/flexbuf1'), ('flexbuf0', '/mnt/flexbuf0'), ('vortex', '/mnt/vortex'), ('colossos', '/mnt/colossos')], max_length=16, primary_key=True, serialize=False),
        ),
    ]
