# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-09 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_auto_20181009_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
