# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-09 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_module_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='updated',
        ),
    ]
