# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_remove_module_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='modified',
            field=models.DateField(help_text='Set by postgresl function triggered on update', null=True),
        ),
    ]
