# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-12 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_module_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='location',
            new_name='ip',
        ),
    ]
