# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_auto_20181016_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='freespace',
            field=models.CharField(blank=True, help_text='Available space in TB', max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='ip',
            field=models.CharField(blank=True, help_text='IP address', max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='port',
            field=models.CharField(blank=True, help_text='Port number', max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='server_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='transferrate',
            field=models.CharField(blank=True, help_text='Available transfer bandwidth', max_length=100),
        ),
    ]
