# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-28 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20181016_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='transfer_to_correlator',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Transfer to correlator status', max_length=1),
        ),
    ]
