# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_auto_20181029_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='module_to_raid',
            field=models.CharField(blank=True, choices=[('p', 'Pending copy'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Module upload to raid status', max_length=1),
        ),
    ]
