# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_auto_20181029_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='ship',
            field=models.CharField(help_text='Shipping reference', max_length=20, null=True),
        ),
    ]
