# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_module_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='ship',
            field=models.CharField(blank=True, help_text='Shipping reference', max_length=20, null=True),
        ),
    ]
