# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_auto_20181101_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'permissions': (('can_ship', 'Set module shipping reference'),)},
        ),
    ]
