# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_auto_20181127_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='free',
            field=models.IntegerField(blank=True, default='2000', help_text='Free space in GB', null=True),
        ),
    ]
