# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_auto_20181217_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='free',
            field=models.IntegerField(blank=True, help_text='Free space in GB', null=True),
        ),
    ]
