# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_auto_20190429_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='station',
            field=models.CharField(blank=True, choices=[('ke', 'Katherine'), ('ho', 'Hobart26'), ('hb', 'Hobart12'), ('yg', 'Yarragadee'), ('cd', 'Ceduna'), ('ti', 'Tidbinbilla'), ('ya', 'Yamaguchi'), ('hi', 'Hitachi'), ('kb', 'Kashima')], help_text='Station two letter i.d.', max_length=2),
        ),
    ]
