# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-23 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_auto_20190708_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='VBS_record',
            fields=[
                ('name', models.CharField(choices=[('FLXBUFHB', 'flexbuffhb'), ('FLXBUFCD', 'flexbuffcd'), ('FLXBUFKE', 'flexbuffcd'), ('FLXBUFYG', 'flexbuffcd'), ('FLXBUF', 'flexbuf'), ('FLXBUFLKE', 'flexbuffcd'), ('FLXBUFLYG', 'flexbuffcd')], max_length=16, primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, help_text='IP address', max_length=16)),
                ('freespace', models.DecimalField(decimal_places=1, help_text='Available space in TB one decimal place', max_digits=4, null=True)),
            ],
        ),
    ]
