# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0095_vbs_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentinstance',
            name='vbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.VBS_record'),
        ),
    ]
