# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-18 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0096_experimentinstance_vbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbs_record',
            name='name',
            field=models.CharField(choices=[('FLXBUFHB', 'flexbuffhb'), ('FLXBUFCD', 'flexbuffcd'), ('FLXBUFKE', 'flexbuffke'), ('FLXBUFYG', 'flexbuffyg'), ('FLXBUF', 'flexbuf'), ('FLXBUFLKE', 'flexbuflke'), ('FLXBUFLYG', 'flexbuflyg')], max_length=16, primary_key=True, serialize=False),
        ),
    ]
