# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0097_auto_20200218_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='size',
            field=models.DecimalField(decimal_places=1, help_text='Total space in TB one decimal place', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='location',
            field=models.CharField(choices=[('ke', 'Katherine'), ('ho', 'Hobart'), ('yg', 'Yarragadee'), ('cd', 'Ceduna'), ('ti', 'Tidbinbilla'), ('wn', 'Washington'), ('ff', 'Failed')], help_text='Enter new (destination) location', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(choices=[('bfg8', '/mnt/bfg8'), ('bfg16', '/mnt/bfg16'), ('IVS', '/mnt/rd1/IVS'), ('IVS1', '/mnt/rdsi/IVS'), ('godzilla8', '/mnt/godzilla8'), ('godzilla16', '/mnt/godzilla16'), ('cornucopia', '/mnt/cornucopia'), ('AUSTRAL', '/mnt/rd1/AUSTRAL'), ('AUSTRAL1', '/mnt/rdsi/AUSTRAL'), ('astro', '/mnt/rd1/astro'), ('astro1', '/mnt/rd1/astro'), ('LBA', '/mnt/rd1/LBA'), ('LBA1', '/mnt/rdsi/LBA'), ('jupiter', '/mnt/RAID'), ('jupiter2', '/mnt/RAID2'), ('sirius8', '/mnt/sirius8'), ('sirius16', '/mnt/sirius16'), ('flexbuf3', '/mnt/flexbuf3'), ('flexbuf2', '/mnt/flexbuf2'), ('flexbuf1', '/mnt/flexbuf1'), ('flexbuf0', '/mnt/flexbuf0'), ('vortex', '/mnt/vortex'), ('colossos', '/mnt/colossos'), ('flxbffhb', 'flexbuffhb'), ('flxbffyg', 'flexbuffyg'), ('flxbffke', 'flexbuffke'), ('flxbffcd', 'flexbuffcd'), ('flxbflke', 'flexbuflke'), ('flxbflyg', 'flexbuflyg')], max_length=16, primary_key=True, serialize=False),
        ),
    ]
