# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-20 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0098_auto_20200320_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentinstance',
            name='vbs',
        ),
        migrations.DeleteModel(
            name='VBS_record',
        ),
    ]
