# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0099_auto_20200320_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='freespace',
            field=models.DecimalField(decimal_places=1, help_text='Available space in TB one decimal place', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='size',
            field=models.DecimalField(decimal_places=1, help_text='Total space in TB one decimal place', max_digits=6, null=True),
        ),
    ]
