# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0101_auto_20200323_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='freespace',
            field=models.IntegerField(help_text='Available space in TB', null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='size',
            field=models.IntegerField(help_text='Total space in TB ', null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='freespace',
            field=models.IntegerField(blank=True, help_text='Available space in TB'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='transferrate',
            field=models.IntegerField(blank=True, help_text='Available transfer bandwidth'),
        ),
    ]
