# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0105_experimentinstance_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentinstance',
            name='to_hobart',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Transferred to Hobart storage', max_length=1),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='module_to_raid',
            field=models.CharField(blank=True, choices=[('p', 'Pending copy'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Recording has been copied', max_length=1),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='station',
            field=models.CharField(blank=True, choices=[('ke', 'Katherine'), ('ho', 'Hobart26'), ('hb', 'Hobart12'), ('yg', 'Yarragadee'), ('cd', 'Ceduna'), ('td', 'Tidbinbilla'), ('ya', 'Yamaguchi'), ('hi', 'Hitachi'), ('kb', 'Kashima'), ('wa', 'Warkworth')], help_text='Station two letter i.d.', max_length=2),
        ),
        migrations.AlterField(
            model_name='module',
            name='location',
            field=models.CharField(choices=[('ke', 'Katherine'), ('ho', 'Hobart'), ('yg', 'Yarragadee'), ('cd', 'Ceduna'), ('td', 'Tidbinbilla'), ('wn', 'Washington'), ('ff', 'Failed')], help_text='Enter new (destination) location', max_length=2, null=True),
        ),
    ]
