# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-09-02 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0107_auto_20200902_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentinstance',
            old_name='module_to_raid',
            new_name='extract',
        ),
        migrations.RenameField(
            model_name='experimentinstance',
            old_name='transfer_to_correlator',
            new_name='transfer',
        ),
    ]
