# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0108_auto_20200902_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='path',
            field=models.CharField(blank=True, help_text='path on local Hobart store raid (see raid column)', max_length=256, null=True),
        ),
    ]
