# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-01-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0109_auto_20210225_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField(blank=True, help_text='Recorded scan data in Bytes', null=True)),
                ('etx', models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='scan copied from original', max_length=1)),
                ('htx', models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='scan moved to local store; here', max_length=1)),
                ('ctx', models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='scan transferred to correlator', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='extract',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='Recording has been copied', max_length=1),
        ),
        migrations.AlterField(
            model_name='experimentinstance',
            name='scans',
            field=models.IntegerField(blank=True, help_text='Total number of scans', null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ExperimentInstance'),
        ),
    ]
