# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0110_auto_20240129_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
