# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-03 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0112_auto_20240403_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='etx',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Copying'), ('u', 'Uploaded'), ('f', 'Failed')], default='p', help_text='scan copied from original', max_length=1, null=True),
        ),
    ]
