# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-03 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0117_auto_20240403_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Recorded scan data in Bytes', null=True),
        ),
    ]
