# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-05 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0118_auto_20240403_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='ctx',
            field=models.BooleanField(default=False, help_text='scan transferred to correlator'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='etx',
            field=models.BooleanField(default=False, help_text='scan copied from original'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='htx',
            field=models.BooleanField(default=False, help_text='scan moved to local store; here at hobart'),
        ),
    ]
